import {
  Dumbbell, Utensils, Brain, Moon, Flag, Trophy, Camera, Award,
  Footprints, Droplet, Droplets, Flame, ChevronRight, X, ArrowUp, ArrowDown,
  Zap, Scale, Target, HelpCircle, Star, Heart, CheckCircle2,
  AlertTriangle, Info, Bike, Apple, Coffee, Bed, Wind,
  Swords, Medal, Crown, Timer, BarChart2, TrendingUp, TrendingDown,
  Activity, Waves, Sun, Sunrise, BookOpen, Headphones, Pencil,
  PhoneOff, ShowerHead, Sandwich, GlassWater,
  Weight, Ruler, ArrowRight, CircleDot, Milestone,
  Home, PenLine, Eye, CalendarDays, LayoutGrid,
  Lock, Unlock, ChevronDown, Plus, Check, Image, Quote,
  Download, Printer, LineChart, RefreshCw,
} from 'lucide-react'

const ICON_MAP = {
  // Nav
  home:             Home,
  edit:             PenLine,
  'pen-line':       PenLine,
  penline:          PenLine,
  eye:              Eye,
  calendar:         CalendarDays,
  'calendar-days':  CalendarDays,
  grid:             LayoutGrid,
  'layout-grid':    LayoutGrid,
  layoutgrid:       LayoutGrid,
  // Lanes
  dumbbell:         Dumbbell,
  utensils:         Utensils,
  brain:            Brain,
  moon:             Moon,
  // Checkpoints / achievements
  flag:             Flag,
  trophy:           Trophy,
  award:            Award,
  camera:           Camera,
  medal:            Medal,
  crown:            Crown,
  milestone:        Milestone,
  lock:             Lock,
  unlock:           Unlock,
  // Alerts / status
  footprints:       Footprints,
  droplet:          Droplet,
  droplets:         Droplets,
  flame:            Flame,
  fire:             Flame,
  'chevron-right':  ChevronRight,
  chevronright:     ChevronRight,
  'chevron-down':   ChevronDown,
  chevrondown:      ChevronDown,
  x:                X,
  check:            Check,
  'check-circle':   CheckCircle2,
  checkcircle:      CheckCircle2,
  plus:             Plus,
  'arrow-up':       ArrowUp,
  arrowup:          ArrowUp,
  'arrow-down':     ArrowDown,
  arrowdown:        ArrowDown,
  'arrow-right':    ArrowRight,
  arrowright:       ArrowRight,
  'trending-up':    TrendingUp,
  trendingup:       TrendingUp,
  'trending-down':  TrendingDown,
  trendingdown:     TrendingDown,
  // Vision tile types
  image:            Image,
  quote:            Quote,
  // Insights / actions
  download:         Download,
  printer:          Printer,
  'line-chart':     LineChart,
  linechart:        LineChart,
  // KPIs / stats
  zap:              Zap,
  scale:            Scale,
  target:           Target,
  goal:             Target,
  activity:         Activity,
  'refresh-cw':     RefreshCw,
  refreshcw:        RefreshCw,
  refresh:          RefreshCw,
  'bar-chart':      BarChart2,
  barchart:         BarChart2,
  timer:            Timer,
  // Habits
  'book-open':      BookOpen,
  bookopen:         BookOpen,
  headphones:       Headphones,
  pencil:           Pencil,
  'phone-off':      PhoneOff,
  phoneoff:         PhoneOff,
  shower:           ShowerHead,
  showerhead:       ShowerHead,
  sandwich:         Sandwich,
  'glass-water':    GlassWater,
  glasswater:       GlassWater,
  apple:            Apple,
  coffee:           Coffee,
  bed:              Bed,
  wind:             Wind,
  bike:             Bike,
  sun:              Sun,
  sunrise:          Sunrise,
  waves:            Waves,
  swords:           Swords,
  star:             Star,
  heart:            Heart,
  'alert-triangle': AlertTriangle,
  alerttriangle:    AlertTriangle,
  info:             Info,
  ruler:            Ruler,
  weight:           Weight,
  'circle-dot':     CircleDot,
  circledot:        CircleDot,
}

export function Icon({ name = '', size = 16, color, strokeWidth = 1.75, className = '' }) {
  const key  = (name || '').toLowerCase().replace(/[_\s]/g, '-')
  const Comp = ICON_MAP[key] || ICON_MAP[key.replace(/-/g, '')] || HelpCircle
  return <Comp size={size} color={color} strokeWidth={strokeWidth} className={className} />
}
